version: "3.7"

services:
  rentalx-db:
    image: postgres
    container_name: rentalx-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - rentalx-db
    depends_on:
      - rentalx-db

volumes:
  pgdata:
    driver: local
